services:
  db:
    image: postgres:16.3
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DATASOURCE_USER}
      - POSTGRES_USER=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./config/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres:
