services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres:
