services:
  server:
    build:
      context: .
    env_file: .env.docker
    ports:
      - 8090:8090
    networks:
      - app
    depends_on:
      - db
      - keycloak

  db:
    image: postgres:16.3
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DATASOURCE_USER}
      - POSTGRES_USER=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    restart: always
    env_file: .env
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command:
      - start-dev
      - --proxy-headers=forwarded
    ports:
      - 8080:8080
      - 8443:8443
      - 9000:9000
    networks:
      - app
    depends_on:
      - db
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - app

  nginx:
    image: nginx:latest
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - app
    depends_on:
      - server

  # Generate token -> bin/elasticsearch-create-enrollment-token --scope kibana
  # Generate password -> bin/elasticsearch-setup-passwords interactive
  elastic:
    image: elasticsearch:8.15.0
    volumes:
      - elastic:/usr/share/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app

  kibana:
    image: kibana:8.15.0
    volumes:
      - kibana:/usr/share/kibana
    ports:
      - 5601:5601
    networks:
      - app
    depends_on:
      - elastic

networks:
  app:
    driver: bridge

volumes:
  postgres:
  elastic:
  kibana:
